### ISSUE TITLE
How to get callback to work.

### ISSUE THREAD

**Issue by strunkie30** [bunqCommunity/bunqJSClient#28]
Hej All,

Is there an example available how to use certificate pinning? My callback doesn't trigger and I think that certificate pinning must be configured somewhere..

**Comment by Crecket** [comment]
I think that something else is going on if you're not receiving callbacks. If you check the server logs do you see any requests coming in? 

This library was built for client-side JS apps and although we support NodeJS servers now it doesn't include things like callback handling and certificate pinning for now.

**Comment by strunkie30** [comment]
I've solved the issue by adding the certificate-pinned endpoints. Maybe its an idea to add them to this library for a better nodejs support!
