### ISSUE TITLE
NodeJS example: Error: No public key is set yet, make sure you setup an encryption key with BunqJSClient->setup()

### ISSUE THREAD

**Issue by michelepatrassi** [BunqCommunity/BunqJSClient#38]
### Bug report

repro steps:
- clone project
- install deps using yarn
- yarn build (created first an empty dist folder with a dummy file to make it work)
- cd examples
- renamed the env, updating the API_KEY and the NODE_ENV to development (left the same ENCRYPTION_KEY, I also tried with an autogenerated one)
- node nodejs_example.js

Error: No public key is set yet, make sure you setup an encryption key with BunqJSClient->setup()
    at BunqJSClient.install (/Users/michele/dev/tmi/monnei/bunqJSClient/dist/BunqJSClient.js:170:23)
    at setup (/Users/michele/dev/tmi/monnei/bunqJSClient/examples/nodejs_example.js:45:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)

Probably I'm missing something but the message does not help, I don't see any method named "setup" on BunqJSClient. 
I'm using MacOS, yarn 1.7.0 and node 10.10.0.

**Comment by Crecket** [comment]
That error message is wrong, it should say `run()`, I'll fix that now.

The .env file has to bein the current working directory of your command line. So if you do `cd examples` it should be in the examples folder. Personally I just use `node examples/nodejs_example.js` and leave the .env file in the root of the project.

**Comment by Iar0** [comment]
awesome, works like a charm! I was doing pushing a fix for the error message but I get a 403...how can I contribute?
